### ISSUE TITLE
Can't find the executable file:(

### ISSUE THREAD

**Issue by bijjybox** [patrickpr/CheckPointImport#1]
Hi @patrickpr 
The project seems really helpful. 
While I was going through the documentation for the installation process, it was mentioned that the zipped folder contains an exe file, but sadly couldn't find one. Could you please help me if I am missing some steps.

**Comment by patrickpr** [comment]
Hi, 
The zip file can be fetched in release : [Release](https://github.com/patrickpr/CheckPointImport/releases)

Then assets -> CPImport.zip

**Comment by bijjybox** [comment]
Thanks @patrickpr 
this really helped a lot
